// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentT1708EWebV1.Models;

namespace StudentT1708EWebV1.Migrations
{
    [DbContext(typeof(StudentT1708EWebV1Context))]
    partial class StudentT1708EWebV1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentT1708EWebV1.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentRollNumber");

                    b.Property<int>("SubjectMark");

                    b.Property<string>("SubjectName");

                    b.HasKey("Id");

                    b.HasIndex("StudentRollNumber");

                    b.ToTable("Mark");

                    b.HasData(
                        new { Id = 1, StudentRollNumber = "A002768", SubjectMark = 20, SubjectName = "Java" },
                        new { Id = 2, StudentRollNumber = "A002768", SubjectMark = 25, SubjectName = "C#" },
                        new { Id = 3, StudentRollNumber = "A002768", SubjectMark = 22, SubjectName = "Php" }
                    );
                });

            modelBuilder.Entity("StudentT1708EWebV1.Models.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RollNumber");

                    b.ToTable("Student");

                    b.HasData(
                        new { RollNumber = "A002768", CreatedAt = new DateTime(2018, 11, 6, 19, 28, 9, 337, DateTimeKind.Local), Email = "nguyencong@gmail.com", FirstName = "Nguyen Cong", Status = 1, UpdatedAt = new DateTime(2018, 11, 6, 19, 28, 9, 338, DateTimeKind.Local) },
                        new { RollNumber = "A002238", CreatedAt = new DateTime(2018, 11, 6, 19, 28, 9, 339, DateTimeKind.Local), Email = "duongthu@gmail.com", FirstName = "Duong Thu", Status = 1, UpdatedAt = new DateTime(2018, 11, 6, 19, 28, 9, 339, DateTimeKind.Local) },
                        new { RollNumber = "A001568", CreatedAt = new DateTime(2018, 11, 6, 19, 28, 9, 339, DateTimeKind.Local), Email = "ngocanh@gmail.com", FirstName = "Ngoc Anh", Status = 1, UpdatedAt = new DateTime(2018, 11, 6, 19, 28, 9, 339, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("StudentT1708EWebV1.Models.Mark", b =>
                {
                    b.HasOne("StudentT1708EWebV1.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentRollNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
